---
#Данный плагин был создан Алексем Лозовягиным (http://vk.com/olekseyua)
#Plugin by INFOMCPE.RU(https://github.com/infomcpe)
#█──────██─█████─█─███─█─────█─███████─███████─█─█████─██─────██──────██───────██████─██████──█─────█─
#█─█████─██─███─██──█──██────█─█───────█─────█─█──███──█─█████─█─█████─█─████████████─█─────█─█─────█─
#█─█████─███─█─███──█──█─█───█─█───────█─────█─█─█─█─█─█─███████─█████─█─████████████─█─────█─█─────█─
#█──────█████─████──█──█──█──█─█████───█─────█─█─██─██─█─███████──────██─────████████─██████──█─────█─
#█─█████─████─████──█──█───█─█─█───────█─────█─█─█████─█─███████─███████─████████───█─█───█───█─────█─
#█─█████─████─████──█──█────██─█───────█─────█─█─█████─█─█████─█─███████─████████───█─█────█──█─────█─
#█──────█████─████─███─█─────█─█───────███████─█─█████─██─────██─███████───────██───█─█─────█──█████──
#█████████████████─────────────────────────────██████████████████████████████████████─────────────────

#↓Врямя (в минутах) когда игрок будет новичком
timе-newcomer: "10"